"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Interface } from "ethers";
import { AlertTriangle, Bell, Blocks, CheckCircle2, ExternalLink, Fingerprint, History, Image as ImageIcon, LayoutDashboard, Search, ShieldCheck, Trash2, Wallet } from "lucide-react";
import { CHAINS, ChainId, NftAsset, ScanHistory, TokenApproval, WalletAnalysis, WatchItem, isEvmAddress } from "@/lib/types";
import { authenticatedWallet, authenticateWallet, browserProvider, connectWallet, ensureWalletChain, shortAddress } from "@/lib/wallet";
import SystemStatus from "./SystemStatus";

type PageKind = "scanner" | "portfolio" | "contracts" | "approvals" | "watchlist" | "nfts" | "history";
const sample="0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045";
const nav=[{id:"overview",href:"/",label:"Overview",icon:LayoutDashboard},{id:"scanner",href:"/scanner",label:"Scanner",icon:Search},{id:"portfolio",href:"/portfolio",label:"Portfolio",icon:Wallet},{id:"nfts",href:"/nfts",label:"NFTs",icon:ImageIcon},{id:"contracts",href:"/contracts",label:"Contracts",icon:Blocks},{id:"approvals",href:"/approvals",label:"Approvals",icon:Fingerprint},{id:"watchlist",href:"/watchlist",label:"Watchlist",icon:Bell},{id:"history",href:"/history",label:"Scan history",icon:History}];

export default function FeaturePage({kind}:{kind:PageKind}) {
 const [address,setAddress]=useState(sample),[chain,setChain]=useState<ChainId>("ethereum"),[data,setData]=useState<WalletAnalysis|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 const [watchlist,setWatchlist]=useState<WatchItem[]>([]);
 const [approvals,setApprovals]=useState<TokenApproval[]|null>(null);
 const [nfts,setNfts]=useState<NftAsset[]|null>(null),[history,setHistory]=useState<ScanHistory[]>([]),[label,setLabel]=useState("");
 const [connected,setConnected]=useState("");
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const linkedAddress=params.get("address"),linkedChain=params.get("chain") as ChainId|null;if(linkedAddress&&isEvmAddress(linkedAddress))setAddress(linkedAddress);if(linkedChain&&CHAINS[linkedChain])setChain(linkedChain);authenticatedWallet().then(setConnected);if(kind==="watchlist")loadWatchlist();if(kind==="history")loadHistory()},[kind]);
 async function loadWatchlist(){try{const r=await fetch("/api/watchlist",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setWatchlist(b)}catch(e){setMessage(e instanceof Error?e.message:"Could not load watchlist")}}
 async function loadHistory(){try{const r=await fetch("/api/history",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setHistory(b)}catch(e){setMessage(e instanceof Error?e.message:"Could not load scan history")}}
 async function analyze(){if(!isEvmAddress(address)){setMessage("Enter a valid EVM address.");return}setLoading(true);setMessage("");try{if(kind==="approvals"||kind==="nfts"){const r=await fetch(`/api/${kind}?address=${encodeURIComponent(address)}&chain=${chain}`);const b=await r.json();if(!r.ok)throw new Error(b.error);if(kind==="approvals")setApprovals(b);else setNfts(b)}else{const r=await fetch("/api/analyze-wallet",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address,chain})});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}}catch(e){setMessage(e instanceof Error?e.message:"Analysis failed")}finally{setLoading(false)}}
 async function addWatch(){if(!isEvmAddress(address))return setMessage("Enter a valid EVM address.");setLoading(true);try{const r=await fetch("/api/watchlist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address,chain,label})});const b=await r.json();if(!r.ok)throw new Error(b.error);await loadWatchlist();setLabel("");setMessage("Address saved in PostgreSQL.")}catch(e){setMessage(e instanceof Error?e.message:"Could not save address")}finally{setLoading(false)}}
 async function removeWatch(id:string){try{const r=await fetch(`/api/watchlist?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(!r.ok)throw new Error("Delete failed");setWatchlist(watchlist.filter(x=>x.id!==id))}catch(e){setMessage(e instanceof Error?e.message:"Could not delete address")}}
 async function connect(){try{setMessage("Approve the signature in your wallet. This is free and does not create a transaction.");const account=await authenticateWallet();setConnected(account);setAddress(account);setMessage("Wallet authenticated. Your private watchlist is ready.");if(kind==="watchlist")await loadWatchlist()}catch(e){setMessage(e instanceof Error?e.message:"Wallet sign-in failed")}}
 const titles={scanner:["Universal scanner","Investigate any EVM wallet across five supported networks."],portfolio:["Portfolio intelligence","Inspect live on-chain balances and activity."],nfts:["NFT explorer","Discover NFTs owned by any public EVM address."],contracts:["Smart contract analyzer","Inspect deployed bytecode and behavioral risk."],approvals:["Token approval manager","Find active ERC-20 allowances and revoke them with MetaMask."],watchlist:["Address watchlist","Save important addresses and labels in PostgreSQL."],history:["Analysis history","Review the latest AI assessments stored in PostgreSQL."]};
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brandMark"><ShieldCheck size={21}/></span><span>Sentinel<span>3</span></span></div><nav>{nav.map(n=><Link className={n.id===kind?"active":""} href={n.href} key={n.id}><n.icon/>{n.label}</Link>)}</nav><SystemStatus/></aside><section className="workspace"><header><div><p className="eyebrow">SENTINEL3 / {kind.toUpperCase()}</p><h1>{titles[kind][0]}</h1><p className="subtitle">{titles[kind][1]}</p></div><button className="connect" onClick={connect}><Wallet size={16}/>{connected?shortAddress(connected):"Sign in with wallet"}</button></header>
 {kind!=="history"&&<div className="scanner card"><div className="field"><label>{kind==="contracts"?"CONTRACT ADDRESS":"WALLET ADDRESS"}</label><div><Search/><input value={address} onChange={e=>setAddress(e.target.value)}/></div>{kind==="watchlist"&&<input className="labelInput" value={label} onChange={e=>setLabel(e.target.value)} placeholder="Optional label, e.g. Treasury"/>}</div><div className="network"><label>NETWORK</label><select value={chain} onChange={e=>setChain(e.target.value as ChainId)}>{Object.values(CHAINS).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><button className="scan" onClick={kind==="watchlist"?addWatch:analyze} disabled={loading}>{loading?"Analyzing…":kind==="watchlist"?"Add address":"Run analysis"}</button>{message&&<p className="notice">{message}</p>}</div>}
 {kind==="history"?<HistoryList rows={history}/>:kind==="watchlist"?<section className="card panel featureBlock"><div className="panelHead"><div><span>POSTGRESQL PERSISTENCE</span><h3>Monitored addresses</h3></div><Bell/></div>{watchlist.length===0?<div className="empty compact"><p>Your watchlist is empty. Add an address above.</p></div>:watchlist.map((w,i)=><div className="watchRow" key={w.id}><span><b>{i+1}</b><span><strong>{w.label||`${w.address.slice(0,10)}…${w.address.slice(-8)}`}</strong><small>{w.label?`${w.address.slice(0,10)}…${w.address.slice(-8)} · `:""}{w.chain} · monitoring enabled</small></span></span><Link className="rowAction" href={`/scanner?address=${w.address}&chain=${w.chain}`}>Scan</Link><button aria-label={`Remove ${w.label||w.address}`} onClick={()=>removeWatch(w.id)}><Trash2/></button></div>)}</section>:kind==="approvals"&&approvals?<Approvals rows={approvals} owner={address} chain={chain}/>:kind==="nfts"&&nfts?<NftGallery rows={nfts} chain={chain}/>:!data?<div className="empty"><div>{kind==="contracts"?<Blocks/>:kind==="approvals"?<Fingerprint/>:kind==="nfts"?<ImageIcon/>:<Search/>}</div><h3>Ready for live analysis</h3><p>Use the example public address or enter another valid EVM address. No generated fallback data is used.</p></div>:kind==="portfolio"?<Portfolio data={data}/>:kind==="contracts"?<Contracts data={data}/>:<ScanResults data={data}/>}</section></main>
}

function NftGallery({rows,chain}:{rows:NftAsset[],chain:ChainId}){return <section className="card panel featureBlock"><div className="panelHead"><div><span>LIVE NFT OWNERSHIP</span><h3>{rows.length} NFTs found</h3></div><ImageIcon/></div>{rows.length===0?<div className="empty compact"><p>No NFTs were returned for this address on {CHAINS[chain].name}.</p></div>:<div className="nftGrid">{rows.map(nft=><a href={`${CHAINS[chain].explorer}/token/${nft.contractAddress}?a=${nft.tokenId}`} target="_blank" rel="noreferrer" key={`${nft.contractAddress}:${nft.tokenId}`}><div className="nftImage">{nft.imageUrl?<img src={nft.imageUrl} alt=""/>:<ImageIcon/>}</div><strong>{nft.name}</strong><span>{nft.collection}</span><small>{nft.tokenType} · #{nft.tokenId.slice(0,12)}</small></a>)}</div>}</section>}
function HistoryList({rows}:{rows:ScanHistory[]}){return <section className="card panel featureBlock"><div className="panelHead"><div><span>POSTGRESQL AUDIT TRAIL</span><h3>{rows.length} recent assessments</h3></div><History/></div>{rows.length===0?<div className="empty compact"><p>Run a wallet analysis to create the first history entry.</p></div>:<div className="historyList">{rows.map(row=><div className="historyRow" key={row.id}><span className={`riskPill ${row.riskLevel.toLowerCase()}`}>{row.riskLevel}</span><span><strong>{row.address.slice(0,10)}…{row.address.slice(-8)}</strong><small>{row.chain} · {new Date(row.analyzedAt).toLocaleString()}</small></span><b>{Math.round(row.riskScore)}/100</b><a href={`/scanner?address=${row.address}&chain=${row.chain}`}><ExternalLink/></a></div>)}</div>}</section>}

function ScanResults({data}:{data:WalletAnalysis}){return <div className="featureGrid"><article className="card featureCard"><ShieldCheck/><span>AI RISK SCORE</span><strong>{data.risk.score}/100</strong><small>{data.risk.level} risk · {Math.round(data.risk.confidence*100)}% confidence</small></article><article className="card featureCard"><Wallet/><span>PRICED PORTFOLIO</span><strong>{data.portfolioValue?`$${data.portfolioValue.toLocaleString(undefined,{maximumFractionDigits:2})}`:"Price unavailable"}</strong><small>{data.transactionCount} recorded transactions</small></article><article className="card panel wide"><h3>Security findings</h3>{data.risk.factors.map((f,i)=><div className="finding" key={f}>{i===2?<AlertTriangle/>:<CheckCircle2/>}{f}</div>)}</article></div>}
function Portfolio({data}:{data:WalletAnalysis}){return <article className="card panel featureBlock"><div className="panelHead"><div><span>LIVE BLOCKCHAIN DATA</span><h3>{data.assets.length} detected assets</h3></div><Wallet/></div><div className="assetList">{data.assets.map(a=><div key={a.contractAddress??a.symbol}><b>{a.symbol}</b><span>{a.name}</span><span>{a.balance.toLocaleString(undefined,{maximumFractionDigits:6})} {a.symbol}</span><strong>{a.valueUsd===null?"Unpriced":`$${a.valueUsd.toLocaleString(undefined,{maximumFractionDigits:2})}`}</strong><small className={(a.change24h??0)>=0?"positive":"negative"}>{a.change24h===null?"—":`${a.change24h>=0?"+":""}${a.change24h.toFixed(2)}%`}</small></div>)}</div></article>}
function Contracts({data}:{data:WalletAnalysis}){return <div className="featureGrid"><article className="card featureCard safeCard">{data.contract.isContract?<CheckCircle2/>:<AlertTriangle/>}<span>ADDRESS TYPE</span><strong>{data.contract.isContract?"Contract":"Wallet"}</strong><small>Read directly with eth_getCode</small></article><article className="card featureCard"><Blocks/><span>DEPLOYED BYTECODE</span><strong>{data.contract.bytecodeBytes.toLocaleString()} bytes</strong><small>Latest confirmed block</small></article><article className="card panel wide"><h3>Behavioral analysis</h3>{data.risk.factors.map(f=><div className="finding" key={f}><ShieldCheck/>{f}</div>)}</article></div>}
function Approvals({rows,owner,chain}:{rows:TokenApproval[],owner:string,chain:ChainId}){const [pending,setPending]=useState(""),[status,setStatus]=useState("");async function revoke(row:TokenApproval){setStatus("");setPending(row.tokenAddress+row.spender);try{const account=await connectWallet();if(account.toLowerCase()!==owner.toLowerCase())throw new Error(`Connect the scanned wallet ${shortAddress(owner)} before revoking.`);await ensureWalletChain(chain);const provider=browserProvider();if(!provider)throw new Error("No wallet provider found.");const data=new Interface(["function approve(address spender,uint256 amount)"]).encodeFunctionData("approve",[row.spender,0]);const hash=await provider.request({method:"eth_sendTransaction",params:[{from:account,to:row.tokenAddress,data}]}) as string;setStatus(`Revocation submitted: ${shortAddress(hash)}`)}catch(error){setStatus(error instanceof Error?error.message:"Revocation was cancelled.")}finally{setPending("")}}return <article className="card panel featureBlock"><div className="panelHead"><div><span>LIVE ERC-20 ALLOWANCES</span><h3>{rows.length} active approvals</h3></div><Fingerprint/></div>{status&&<p className="txStatus">{status}</p>}{rows.length===0?<div className="empty compact"><p>No active approvals were found in the indexed block window.</p></div>:rows.map(row=><div className="approvalRow" key={row.tokenAddress+row.spender}><span className={`status ${row.unlimited?"danger":"warning"}`}>{row.unlimited?"unlimited":"active"}</span><span><strong>{row.tokenSymbol}</strong><small>Spender {shortAddress(row.spender)}</small></span><button disabled={pending===row.tokenAddress+row.spender} onClick={()=>revoke(row)}>{pending===row.tokenAddress+row.spender?"Confirm in wallet":"Revoke"}</button></div>)}</article>}
