"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowUpRight, Bell, Blocks, CheckCircle2, Copy, Eye, Fingerprint, Gauge, History, Image as ImageIcon, LayoutDashboard, Search, ShieldCheck, Sparkles, Wallet, Zap } from "lucide-react";
import { CHAINS, ChainId, WalletAnalysis, isEvmAddress } from "@/lib/types";
import { authenticatedWallet, authenticateWallet, shortAddress } from "@/lib/wallet";
import SystemStatus from "./SystemStatus";

const sample = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045";
const short = shortAddress;

export default function WalletScanner() {
  const [address, setAddress] = useState(sample); const [chain, setChain] = useState<ChainId>("ethereum");
  const [data, setData] = useState<WalletAnalysis | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [connected, setConnected] = useState("");
  const maxActivity = useMemo(() => Math.max(...(data?.activity.map(x => x.transactions) ?? [1])), [data]);
  const scan=useCallback(async (persist=true) => { if (!isEvmAddress(address)) return setError("Enter a valid 0x wallet address."); setLoading(true); setError(""); try { const res = await fetch("/api/analyze-wallet", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ address, chain, persist }) }); const body = await res.json(); if (!res.ok) throw new Error(body.error); setData(body); } catch (e) { setError(e instanceof Error ? e.message : "Scan failed"); } finally { setLoading(false); } },[address,chain]);
  useEffect(()=>{if(!data)return;const timer=setInterval(()=>scan(false),30000);return()=>clearInterval(timer)},[data,scan]);
  useEffect(()=>{authenticatedWallet().then(setConnected)},[]);
  async function connect() { try { const account=await authenticateWallet();setConnected(account);setAddress(account);setError(""); } catch(error) { setError(error instanceof Error?error.message:"Wallet sign-in was cancelled."); } }
  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="brandMark"><ShieldCheck size={21}/></span><span>Sentinel<span>3</span></span></div><nav><Link className="active" href="/"><LayoutDashboard/>Overview</Link><Link href="/scanner"><Search/>Scanner</Link><Link href="/portfolio"><Wallet/>Portfolio</Link><Link href="/nfts"><ImageIcon/>NFTs</Link><Link href="/contracts"><Blocks/>Contracts</Link><Link href="/approvals"><Fingerprint/>Approvals</Link><Link href="/watchlist"><Bell/>Watchlist</Link><Link href="/history"><History/>Scan history</Link></nav><SystemStatus/></aside>
    <section className="workspace"><header><div><p className="eyebrow">WEB3 SECURITY INTELLIGENCE</p><h1>Wallet Command Center</h1></div><button className="connect" onClick={connect}><Wallet size={17}/>{connected ? short(connected) : "Sign in with wallet"}</button></header>
      <div className="hero card"><div><span className="live"><Sparkles size={13}/> AI-POWERED MULTI-CHAIN ANALYSIS</span><h2>Know what is behind<br/><em>every address.</em></h2><p>Screen wallet behavior, assets, contracts, approvals and transaction risk across leading EVM networks.</p><div className="chainBadges">{Object.values(CHAINS).map((item,index)=><span key={item.id}><i style={{background:item.color}}/>{item.name}{index===0&&<b>LIVE</b>}</span>)}</div></div><div className="orb"><ShieldCheck/><span>LIVE<br/>PROTECTION</span></div></div>
      <div className="scanner card"><div className="field"><label>WALLET OR CONTRACT ADDRESS</label><div><Search/><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="0x…"/></div></div><div className="network"><label>NETWORK</label><select value={chain} onChange={e=>setChain(e.target.value as ChainId)}>{Object.values(CHAINS).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><button className="scan" disabled={loading} onClick={()=>scan()}>{loading ? <span className="spinner"/> : <Zap size={17}/>} {loading ? "Analyzing…" : "Analyze wallet"}</button>{error&&<p className="error">{error}</p>}</div>
      {!data ? <section className="launchPad"><div className="launchIntro"><span className="launchIcon"><Gauge/></span><div><span className="eyebrow">READY FOR LIVE INTELLIGENCE</span><h3>One address. Complete security context.</h3><p>Every result is fetched from the selected chain, scored by the AI service, and recorded in PostgreSQL—never replaced with generated fallback data.</p></div><button onClick={()=>scan()}>Start live scan <ArrowUpRight size={15}/></button></div><div className="capabilityGrid"><article className="card capability"><span><ShieldCheck/></span><div><b>Behavioral risk</b><small>AI anomaly scoring and explainable risk factors</small></div><em>01</em></article><article className="card capability"><span><Activity/></span><div><b>Asset intelligence</b><small>Tokens, NFTs, balances and market values</small></div><em>02</em></article><article className="card capability"><span><Fingerprint/></span><div><b>Permission safety</b><small>Inspect and revoke active token allowances</small></div><em>03</em></article></div></section> : <div className="results fade-up"><div className="liveStrip"><span><span className="pulse"/>LIVE DATA</span><small>Updated {new Date(data.analyzedAt).toLocaleTimeString()} · refreshes every 30 seconds</small><button onClick={()=>scan(false)} disabled={loading}>Refresh now</button></div>
        <div className="statgrid"><article className="card stat"><span>PRICED PORTFOLIO</span><strong>{data.portfolioValue?`$${data.portfolioValue.toLocaleString(undefined,{maximumFractionDigits:2})}`:"Pricing unavailable"}</strong><small>{data.assets.length} live assets</small></article><article className="card stat"><span>NATIVE BALANCE</span><strong>{data.balance} {CHAINS[data.chain].symbol}</strong><small>{CHAINS[data.chain].name}</small></article><article className="card stat"><span>TRANSACTIONS</span><strong>{data.transactionCount.toLocaleString()}</strong><small>{data.uniqueInteractions} unique peers</small></article><article className="card risk"><div className={`score ${data.risk.level.toLowerCase()}`}>{data.risk.score}</div><div><span>AI RISK SCORE</span><strong>{data.risk.level} RISK</strong><small>{Math.round(data.risk.confidence*100)}% confidence</small></div></article></div>
        <div className="dashboardGrid"><article className="card panel"><div className="panelHead"><div><span>ACTIVITY SIGNAL</span><h3>Transaction velocity</h3></div><Activity/></div><div className="bars">{data.activity.map(x=><div key={x.day} className="barCol"><div className="bar" style={{height:`${Math.max(8,x.transactions/maxActivity*100)}%`}}/><small>{x.day}</small></div>)}</div></article><article className="card panel riskPanel"><div className="panelHead"><div><span>AI ASSESSMENT</span><h3>Security findings</h3></div><ShieldCheck/></div>{data.risk.factors.map((f,i)=><div className="finding" key={f}>{i===2?<AlertTriangle/>:<CheckCircle2/>}<span>{f}</span></div>)}<div className="mode"><span className="pulse"/> {data.source.toUpperCase()} DATA MODE</div></article></div>
        <article className="card panel"><div className="panelHead"><div><span>ASSET INTELLIGENCE</span><h3>Portfolio</h3></div><Eye/></div><div className="assets">{data.assets.map(a=><div key={a.contractAddress??a.symbol}><b>{a.symbol.slice(0,2)}</b><span><strong>{a.name}</strong><small>{a.balance.toLocaleString(undefined,{maximumFractionDigits:5})} {a.symbol}</small></span><span className="assetValue"><strong>{a.valueUsd===null?"Unpriced":`$${a.valueUsd.toLocaleString(undefined,{maximumFractionDigits:2})}`}</strong><small className={(a.change24h??0)>=0?"positive":"negative"}>{a.change24h===null?"—":`${a.change24h>=0?"+":""}${a.change24h.toFixed(2)}%`}</small></span></div>)}</div></article>
        <article className="card panel tx"><div className="panelHead"><div><span>ON-CHAIN ACTIVITY</span><h3>Recent transactions</h3></div><a href={`${CHAINS[data.chain].explorer}/address/${data.address}`} target="_blank">Open explorer <ArrowUpRight/></a></div><div className="table"><div className="tr th"><span>TRANSACTION</span><span>TYPE</span><span>VALUE</span><span>GAS</span><span>STATUS</span></div>{data.transactions.slice(0,8).map(t=><div className="tr" key={t.hash}><span className="mono">{short(t.hash)} <Copy size={12}/></span><span className="tag">{t.type}</span><span>{t.value} {CHAINS[data.chain].symbol}</span><span>{t.gas.toLocaleString()}</span><span className={`status ${t.risk}`}>{t.risk}</span></div>)}</div></article>
      </div>}
    </section>
  </main>;
}
