import type { Asset, ChainId, NftAsset } from "./types";
const hosts:Record<ChainId,string>={ethereum:"eth-mainnet",polygon:"polygon-mainnet",arbitrum:"arb-mainnet",optimism:"opt-mainnet",bnb:"bnb-mainnet"};
const chainKeys:Record<ChainId,string|undefined>={ethereum:process.env.ALCHEMY_ETHEREUM_API_KEY,polygon:process.env.ALCHEMY_POLYGON_API_KEY,arbitrum:process.env.ALCHEMY_ARBITRUM_API_KEY,optimism:process.env.ALCHEMY_OPTIMISM_API_KEY,bnb:process.env.ALCHEMY_BNB_API_KEY};
const apiKey=(chain:ChainId)=>chainKeys[chain]||process.env.ALCHEMY_API_KEY;
type Envelope<T>={result?:T;error?:{message:string}};
export async function rpc<T>(chain:ChainId,method:string,params:unknown[]):Promise<T>{const key=apiKey(chain);if(!key)throw new Error(`Alchemy API key for ${chain} is not configured.`);const response=await fetch(`https://${hosts[chain]}.g.alchemy.com/v2/${key}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method,params}),signal:AbortSignal.timeout(20000),cache:"no-store"});if(!response.ok)throw new Error(`Blockchain provider returned HTTP ${response.status}`);const payload=await response.json() as Envelope<T>;if(payload.error)throw new Error(payload.error.message);if(payload.result===undefined)throw new Error("Blockchain provider returned no result");return payload.result}
type RawTransfer={hash:string;from:string;to?:string;value?:number;category:string;metadata?:{blockTimestamp?:string}};
export async function fetchTransfers(chain:ChainId,address:string){const base={fromBlock:"0x0",toBlock:"latest",category:["external","internal","erc20","erc721","erc1155"],withMetadata:true,excludeZeroValue:false,maxCount:"0x3e8",order:"desc"};const [outgoing,incoming]=await Promise.all([rpc<{transfers:RawTransfer[]}>(chain,"alchemy_getAssetTransfers",[{...base,fromAddress:address}]),rpc<{transfers:RawTransfer[]}>(chain,"alchemy_getAssetTransfers",[{...base,toAddress:address}])]);const unique=new Map<string,RawTransfer>();for(const tx of [...outgoing.transfers,...incoming.transfers])unique.set(`${tx.hash}:${tx.from}:${tx.to}:${tx.category}`,tx);return [...unique.values()].map(tx=>({...tx,timestamp:tx.metadata?.blockTimestamp?Math.floor(new Date(tx.metadata.blockTimestamp).getTime()/1000):0})).sort((a,b)=>b.timestamp-a.timestamp)}

type TokenBalance={contractAddress:string;tokenBalance:string};
type TokenMetadata={decimals?:number;name?:string;symbol?:string};
const pricePlatforms:Record<ChainId,string>={ethereum:"ethereum",polygon:"polygon-pos",arbitrum:"arbitrum-one",optimism:"optimistic-ethereum",bnb:"binance-smart-chain"};
const nativePriceIds:Record<ChainId,string>={ethereum:"ethereum",polygon:"matic-network",arbitrum:"ethereum",optimism:"ethereum",bnb:"binancecoin"};
export async function fetchTokenAssets(chain:ChainId,address:string):Promise<Asset[]>{
 const result=await rpc<{tokenBalances:TokenBalance[]}>(chain,"alchemy_getTokenBalances",[address,"DEFAULT_TOKENS"]);const nonzero=result.tokenBalances.filter(x=>x.tokenBalance&&x.tokenBalance!=="0x0").slice(0,30);
 const enriched=await Promise.all(nonzero.map(async token=>{try{const meta=await rpc<TokenMetadata>(chain,"alchemy_getTokenMetadata",[token.contractAddress]);const decimals=meta.decimals??18;const balance=Number(BigInt(token.tokenBalance))/10**decimals;return{address:token.contractAddress,meta,balance}}catch{return null}}));
 const valid=enriched.filter((x):x is NonNullable<typeof x>=>Boolean(x&&Number.isFinite(x.balance)&&x.balance>0));const prices=await fetchTokenPrices(chain,valid.map(x=>x.address));
 return valid.map(({address:contractAddress,meta,balance})=>{const quote=prices[contractAddress.toLowerCase()];return{symbol:meta.symbol??"TOKEN",name:meta.name??"Unknown token",balance,valueUsd:quote?balance*quote.usd:null,change24h:quote?.usd_24h_change??null,kind:"token",contractAddress}});
}
async function fetchTokenPrices(chain:ChainId,addresses:string[]){if(!addresses.length)return{} as Record<string,{usd:number;usd_24h_change?:number}>;try{const url=`https://api.coingecko.com/api/v3/simple/token_price/${pricePlatforms[chain]}?contract_addresses=${addresses.join(",")}&vs_currencies=usd&include_24hr_change=true`;const response=await fetch(url,{signal:AbortSignal.timeout(10000),next:{revalidate:60}});if(!response.ok)return{};return await response.json() as Record<string,{usd:number;usd_24h_change?:number}>}catch{return{}}}
export async function fetchNativePrice(chain:ChainId){try{const id=nativePriceIds[chain];const response=await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=${id}&vs_currencies=usd&include_24hr_change=true`,{signal:AbortSignal.timeout(10000),next:{revalidate:60}});if(!response.ok)return null;const data=await response.json() as Record<string,{usd?:number;usd_24h_change?:number}>;return data[id]?.usd?{usd:data[id].usd!,change24h:data[id].usd_24h_change??null}:null}catch{return null}}

type AlchemyNft={contract?:{address?:string;name?:string};contractAddress?:string;tokenId?:string;name?:string;title?:string;tokenType?:string;image?:{cachedUrl?:string;thumbnailUrl?:string;pngUrl?:string;originalUrl?:string};media?:Array<{gateway?:string;thumbnail?:string}>};
export async function fetchNfts(chain:ChainId,address:string):Promise<NftAsset[]>{
 const key=apiKey(chain);if(!key)throw new Error(`Alchemy API key for ${chain} is not configured.`);
 const url=`https://${hosts[chain]}.g.alchemy.com/nft/v3/${key}/getNFTsForOwner?owner=${encodeURIComponent(address)}&withMetadata=true&pageSize=40`;
 const response=await fetch(url,{signal:AbortSignal.timeout(20000),cache:"no-store"});if(!response.ok)throw new Error(`NFT provider returned HTTP ${response.status}`);
 const result=await response.json() as {ownedNfts?:AlchemyNft[]};
 return (result.ownedNfts??[]).map((nft,index)=>({contractAddress:nft.contract?.address??nft.contractAddress??"",tokenId:nft.tokenId??String(index),name:nft.name??nft.title??`Token #${nft.tokenId??index}`,collection:nft.contract?.name??"Unknown collection",imageUrl:nft.image?.cachedUrl??nft.image?.thumbnailUrl??nft.image?.pngUrl??nft.media?.[0]?.thumbnail??nft.media?.[0]?.gateway??null,tokenType:nft.tokenType??"NFT"})).filter(nft=>nft.contractAddress);
}
