import { Pool } from "pg";
import type { ChainId, ScanHistory, WalletAnalysis, WatchItem } from "./types";
let pool:Pool|undefined;
function db(){const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is not configured");pool??=new Pool({connectionString:url,max:10});return pool}
export async function databaseHealth(){const started=Date.now();await db().query("select 1");return Date.now()-started}
export async function saveAnalysis(result:WalletAnalysis,features:unknown){const client=await db().connect();try{await client.query("begin");await client.query(`insert into wallets(address,chain,risk_score,updated_at) values($1,$2,$3,now()) on conflict(address,chain) do update set risk_score=excluded.risk_score,updated_at=now()`,[result.address.toLowerCase(),result.chain,result.risk.score]);for(const tx of result.transactions)await client.query(`insert into transactions(wallet_address,tx_hash,from_address,to_address,value_eth,gas,timestamp,chain) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(tx_hash,wallet_address,chain) do nothing`,[result.address.toLowerCase(),tx.hash,tx.from,tx.to,tx.value,tx.gas,tx.timestamp,result.chain]);await client.query(`insert into fraud_scores(wallet,risk_score,risk_level,risk_factors,confidence,features,chain) values($1,$2,$3,$4,$5,$6,$7)`,[result.address.toLowerCase(),result.risk.score,result.risk.level,result.risk.factors,result.risk.confidence,features,result.chain]);await client.query("commit")}catch(error){await client.query("rollback");throw error}finally{client.release()}}
export async function listWatchlist(userId:string):Promise<WatchItem[]>{const result=await db().query(`select id,address,chain,label,created_at as "createdAt" from watchlist where user_id=$1 order by created_at desc`,[userId]);return result.rows}
export async function addWatch(userId:string,address:string,chain:ChainId,label?:string):Promise<WatchItem>{const result=await db().query(`insert into watchlist(user_id,address,chain,label) values($1,$2,$3,$4) on conflict(user_id,address,chain) where user_id is not null do update set label=coalesce(excluded.label,watchlist.label) returning id,address,chain,label,created_at as "createdAt"`,[userId,address.toLowerCase(),chain,label||null]);return result.rows[0]}
export async function deleteWatch(userId:string,id:string){await db().query(`delete from watchlist where id=$1 and user_id=$2`,[id,userId])}
export async function listRecentAnalyses():Promise<ScanHistory[]>{const result=await db().query(`select id,wallet as address,chain,risk_score::float as "riskScore",risk_level as "riskLevel",confidence::float as confidence,analyzed_at as "analyzedAt" from fraud_scores order by analyzed_at desc limit 50`);return result.rows}
export async function createLoginChallenge(walletAddress:string,nonceHash:string,message:string){await db().query(`delete from auth_nonces where expires_at<now() or wallet_address=$1`,[walletAddress]);await db().query(`insert into auth_nonces(wallet_address,nonce_hash,message,expires_at) values($1,$2,$3,now()+interval '10 minutes')`,[walletAddress,nonceHash,message])}
export async function consumeLoginChallenge(walletAddress:string,nonceHash:string,message:string){const result=await db().query(`delete from auth_nonces where wallet_address=$1 and nonce_hash=$2 and message=$3 and expires_at>now() returning id`,[walletAddress,nonceHash,message]);return result.rowCount===1}
export async function createUserSession(walletAddress:string,tokenHash:string){const client=await db().connect();try{await client.query("begin");const user=await client.query(`insert into app_users(wallet_address,last_login_at) values($1,now()) on conflict(wallet_address) do update set last_login_at=now() returning id,wallet_address as "walletAddress"`,[walletAddress]);await client.query(`delete from user_sessions where expires_at<now()`);await client.query(`insert into user_sessions(user_id,token_hash,expires_at) values($1,$2,now()+interval '7 days')`,[user.rows[0].id,tokenHash]);await client.query("commit");return user.rows[0]}catch(error){await client.query("rollback");throw error}finally{client.release()}}
export async function findUserSession(tokenHash:string){const result=await db().query(`select u.id,u.wallet_address as "walletAddress",s.expires_at as "expiresAt" from user_sessions s join app_users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now()`,[tokenHash]);return result.rows[0]??null}
export async function deleteUserSession(tokenHash:string){await db().query(`delete from user_sessions where token_hash=$1`,[tokenHash])}
