import { CHAINS, ChainId } from "./types";

export interface Eip1193Provider { request(args:{method:string;params?:unknown[]}):Promise<unknown> }
export function browserProvider():Eip1193Provider|undefined{return (window as typeof window&{ethereum?:Eip1193Provider}).ethereum}
export async function connectWallet(){const provider=browserProvider();if(!provider)throw new Error("No injected wallet found. Install MetaMask or another EIP-1193 wallet.");const accounts=await provider.request({method:"eth_requestAccounts"}) as string[];if(!accounts[0])throw new Error("The wallet did not return an account.");return accounts[0]}
export async function authenticateWallet(){const provider=browserProvider();if(!provider)throw new Error("No injected wallet found. Install MetaMask or another EIP-1193 wallet.");const address=await connectWallet();const challengeResponse=await fetch("/api/auth/nonce",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address})});const challenge=await challengeResponse.json();if(!challengeResponse.ok)throw new Error(challenge.error||"Could not start wallet sign-in.");const signature=await provider.request({method:"personal_sign",params:[challenge.message,address]}) as string;const response=await fetch("/api/auth/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address,message:challenge.message,nonce:challenge.nonce,signature})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Wallet sign-in failed.");return address}
export async function authenticatedWallet(){try{const response=await fetch("/api/auth/session",{cache:"no-store"});const result=await response.json();return result.authenticated?String(result.user.walletAddress):""}catch{return ""}}
export async function ensureWalletChain(chain:ChainId){const provider=browserProvider();if(!provider)throw new Error("No injected wallet found.");const config=CHAINS[chain];try{await provider.request({method:"wallet_switchEthereumChain",params:[{chainId:config.chainIdHex}]})}catch(error){const code=(error as {code?:number}).code;if(code!==4902)throw error;await provider.request({method:"wallet_addEthereumChain",params:[{chainId:config.chainIdHex,chainName:config.name,nativeCurrency:{name:config.symbol,symbol:config.symbol,decimals:18},rpcUrls:[config.rpcUrl],blockExplorerUrls:[config.explorer]}]})}}
export const shortAddress=(value:string)=>`${value.slice(0,6)}…${value.slice(-4)}`;
